# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-script-python Documentation for the list of available functions.

from __future__ import print_function

import os
import struct
import sys

sys.path.append(
    os.environ["PERF_EXEC_PATH"] + "/scripts/python/Perf-Trace-Util/lib/Perf/Trace"
)


from perf_trace_context import *  # noqa: F403
from Core import *  # noqa: F403


_OPCODES = {
    0x00: "flush",
    0x01: "write",
    0x02: "read",
    0x04: "write_uncorrectable",
    0x05: "compare",
    0x08: "write_zeroes",
    0x09: "dataset_management",
    0x0C: "verify",
}


def _opcode_name(op):
    return _OPCODES.get(op, f"unknown(0x{op:02x})")


def _parse_descriptors(descriptors, use_sgl):
    data = bytes(descriptors)
    if use_sgl:
        entries = []
        for i in range(0, len(data) - 15, 16):
            addr, length, r0, r1, r2, dtype = struct.unpack_from("<QIBBBB", data, i)
            entries.append(
                f"{{addr=0x{addr:016x},len={length},"
                f"type=0x{dtype:02x},reserved={r0:02x}{r1:02x}{r2:02x}}}"
            )
        return "[" + ",".join(entries) + "]"
    else:
        entries = []
        for i in range(0, len(data) - 7, 8):
            (addr,) = struct.unpack_from("<Q", data, i)
            entries.append(f"0x{addr:016x}")
        return "[" + ",".join(entries) + "]"


def _decode_sqe(sqe):
    data = bytes(sqe)
    op = data[0]
    info = {"opcode": f"{_opcode_name(op)}(0x{op:02x})"}
    if op in (0x01, 0x02):
        nsid = struct.unpack_from("<I", data, 4)[0]
        prp1 = struct.unpack_from("<Q", data, 24)[0]
        prp2 = struct.unpack_from("<Q", data, 32)[0]
        slba = struct.unpack_from("<Q", data, 40)[0]
        nlb = struct.unpack_from("<H", data, 48)[0] + 1
        info.update(
            nsid=nsid,
            slba=slba,
            nlb=nlb,
            prp1=f"0x{prp1:016x}",
            prp2=f"0x{prp2:016x}",
        )
    return info


def trace_begin():
    print("in trace_begin")


def trace_end():
    print("in trace_end")


def nvme__nvme_pci_complete(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    result,
    sq_head,
    sq_id,
    status,
    retries,
    perf_sample_dict,
):
    print_header(
        event_name, common_cpu, common_secs, common_nsecs, common_pid, common_comm
    )

    print(
        "ctrl_id=%d, qid=%d, cid=%u, "
        "result=%u, sq_head=%u, sq_id=%u, "
        "status=%u, retries=%u"
        % (ctrl_id, qid, cid, result, sq_head, sq_id, status, retries)
    )

    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")

    for node in common_callchain:
        if "sym" in node:
            print(
                "	[%x] %s%s%s%s"
                % (
                    node["ip"],
                    node["sym"]["name"],
                    "+0x{:x}".format(node["sym_off"]) if "sym_off" in node else "",
                    " ({})".format(node["dso"]) if "dso" in node else "",
                    " " + node["sym_srcline"] if "sym_srcline" in node else "",
                )
            )
        else:
            print("	[%x]" % (node["ip"]))

    print()


def nvme__nvme_pci_submit(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    opcode,
    nsid,
    data_len,
    meta_len,
    use_sgl,
    single_segment,
    sqe,
    descriptors,
    perf_sample_dict,
):
    print_header(
        event_name, common_cpu, common_secs, common_nsecs, common_pid, common_comm
    )

    sqe_info = _decode_sqe(sqe)
    desc_str = _parse_descriptors(descriptors, use_sgl)
    sqe_parts = " ".join(f"{k}={v}" for k, v in sqe_info.items())
    print(
        f"ctrl_id={ctrl_id} qid={qid} cid={cid} "
        f"opcode=0x{opcode:02x} nsid={nsid} data_len={data_len} "
        f"meta_len={meta_len} use_sgl={use_sgl} single_segment={single_segment}"
    )
    print(f"  sqe: {sqe_parts}")
    print(f"  descriptors({len(bytes(descriptors))}B): {desc_str}")

    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")

    for node in common_callchain:
        if "sym" in node:
            print(
                "	[%x] %s%s%s%s"
                % (
                    node["ip"],
                    node["sym"]["name"],
                    "+0x{:x}".format(node["sym_off"]) if "sym_off" in node else "",
                    " ({})".format(node["dso"]) if "dso" in node else "",
                    " " + node["sym_srcline"] if "sym_srcline" in node else "",
                )
            )
        else:
            print("	[%x]" % (node["ip"]))

    print()


def trace_unhandled(event_name, context, event_fields_dict, perf_sample_dict):
    print(get_dict_as_string(event_fields_dict))
    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")


def print_header(event_name, cpu, secs, nsecs, pid, comm):
    print(
        "%-20s %5u %05u.%09u %8u %-20s " % (event_name, cpu, secs, nsecs, pid, comm),
        end="",
    )


def get_dict_as_string(a_dict, delimiter=" "):
    return delimiter.join(["%s=%s" % (k, str(v)) for k, v in sorted(a_dict.items())])
