# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-script-python Documentation for the list of available functions.

from __future__ import print_function

import os
import sys

sys.path.append(
    os.environ["PERF_EXEC_PATH"] + "/scripts/python/Perf-Trace-Util/lib/Perf/Trace"
)

# Allow importing nvme_trace_events from the same directory as this script.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from perf_trace_context import *  # noqa: F403
from Core import *  # noqa: F403
from nvme_trace_events import (
    NvmePciComplete,
    NvmePciSubmit,
    parse_complete,
    parse_submit,
)


def trace_begin():
    print("in trace_begin")


def trace_end():
    print("in trace_end")


def nvme__nvme_pci_complete(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    result,
    sq_head,
    sq_id,
    status,
    retries,
    perf_sample_dict,
):
    print_header(
        event_name, common_cpu, common_secs, common_nsecs, common_pid, common_comm
    )

    ev: NvmePciComplete = parse_complete(
        ctrl_id, qid, cid, result, sq_head, sq_id, status, retries
    )
    print(
        f"ctrl_id={ev.ctrl_id} qid={ev.qid} cid={ev.cid} "
        f"result=0x{ev.result:016x} sq_head={ev.sq_head} sq_id={ev.sq_id} "
        f"status=0x{ev.status:04x} retries={ev.retries}"
    )

    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")

    for node in common_callchain:
        if "sym" in node:
            print(
                "	[%x] %s%s%s%s"
                % (
                    node["ip"],
                    node["sym"]["name"],
                    "+0x{:x}".format(node["sym_off"]) if "sym_off" in node else "",
                    " ({})".format(node["dso"]) if "dso" in node else "",
                    " " + node["sym_srcline"] if "sym_srcline" in node else "",
                )
            )
        else:
            print("	[%x]" % (node["ip"]))

    print()


def nvme__nvme_pci_submit(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    opcode,
    nsid,
    data_len,
    meta_len,
    use_sgl,
    single_segment,
    sqe,
    descriptors,
    perf_sample_dict,
):
    print_header(
        event_name, common_cpu, common_secs, common_nsecs, common_pid, common_comm
    )

    ev: NvmePciSubmit = parse_submit(
        ctrl_id,
        qid,
        cid,
        opcode,
        nsid,
        data_len,
        meta_len,
        use_sgl,
        single_segment,
        sqe,
        descriptors,
    )

    sqe_parts = f"opcode={ev.sqe.opcode_str}"
    if ev.sqe.nsid is not None:
        sqe_parts += (
            f" nsid={ev.sqe.nsid} slba={ev.sqe.slba} nlb={ev.sqe.nlb}"
            f" prp1=0x{ev.sqe.prp1:016x} prp2=0x{ev.sqe.prp2:016x}"
        )

    if ev.use_sgl:
        desc_str = (
            "["
            + ",".join(
                f"{{addr=0x{d.addr:016x},len={d.length},"
                f"type=0x{d.desc_type:02x},"
                f"reserved={d.reserved[0]:02x}{d.reserved[1]:02x}{d.reserved[2]:02x}}}"
                for d in ev.sgl_entries
            )
            + "]"
        )
    else:
        desc_str = "[" + ",".join(f"0x{a:016x}" for a in ev.prp_entries) + "]"

    print(
        f"ctrl_id={ev.ctrl_id} qid={ev.qid} cid={ev.cid} "
        f"opcode=0x{ev.opcode:02x} nsid={ev.nsid} data_len={ev.data_len} "
        f"meta_len={ev.meta_len} use_sgl={ev.use_sgl} "
        f"single_segment={ev.single_segment}"
    )
    print(f"  sqe: {sqe_parts}")
    desc_count = len(ev.sgl_entries) if ev.use_sgl else len(ev.prp_entries)
    print(f"  descriptors({desc_count}): {desc_str}")

    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")

    for node in common_callchain:
        if "sym" in node:
            print(
                "	[%x] %s%s%s%s"
                % (
                    node["ip"],
                    node["sym"]["name"],
                    "+0x{:x}".format(node["sym_off"]) if "sym_off" in node else "",
                    " ({})".format(node["dso"]) if "dso" in node else "",
                    " " + node["sym_srcline"] if "sym_srcline" in node else "",
                )
            )
        else:
            print("	[%x]" % (node["ip"]))

    print()


def trace_unhandled(event_name, context, event_fields_dict, perf_sample_dict):
    print(get_dict_as_string(event_fields_dict))
    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")


def print_header(event_name, cpu, secs, nsecs, pid, comm):
    print(
        "%-20s %5u %05u.%09u %8u %-20s " % (event_name, cpu, secs, nsecs, pid, comm),
        end="",
    )


def get_dict_as_string(a_dict, delimiter=" "):
    return delimiter.join(["%s=%s" % (k, str(v)) for k, v in sorted(a_dict.items())])
