# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-script-python Documentation for the list of available functions.

from __future__ import print_function

import os
import sys

sys.path.append(
    os.environ["PERF_EXEC_PATH"] + "/scripts/python/Perf-Trace-Util/lib/Perf/Trace"
)


from perf_trace_context import *  # noqa: F403
from Core import *  # noqa: F403


def trace_begin():
    print("in trace_begin")


def trace_end():
    print("in trace_end")


def nvme__nvme_pci_complete(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    result,
    sq_head,
    sq_id,
    status,
    retries,
    perf_sample_dict,
):
    print_header(
        event_name, common_cpu, common_secs, common_nsecs, common_pid, common_comm
    )

    print(
        "ctrl_id=%d, qid=%d, cid=%u, "
        "result=%u, sq_head=%u, sq_id=%u, "
        "status=%u, retries=%u"
        % (ctrl_id, qid, cid, result, sq_head, sq_id, status, retries)
    )

    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")

    for node in common_callchain:
        if "sym" in node:
            print(
                "	[%x] %s%s%s%s"
                % (
                    node["ip"],
                    node["sym"]["name"],
                    "+0x{:x}".format(node["sym_off"]) if "sym_off" in node else "",
                    " ({})".format(node["dso"]) if "dso" in node else "",
                    " " + node["sym_srcline"] if "sym_srcline" in node else "",
                )
            )
        else:
            print("	[%x]" % (node["ip"]))

    print()


def nvme__nvme_pci_submit(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    opcode,
    nsid,
    data_len,
    meta_len,
    use_sgl,
    single_segment,
    sqe,
    descriptors,
    perf_sample_dict,
):
    print_header(
        event_name, common_cpu, common_secs, common_nsecs, common_pid, common_comm
    )

    print(
        "ctrl_id=%d, qid=%d, cid=%u, "
        "opcode=%u, nsid=%u, data_len=%u, "
        "meta_len=%u, use_sgl=%u, single_segment=%u, "
        "sqe=%s, descriptors=%s"
        % (
            ctrl_id,
            qid,
            cid,
            opcode,
            nsid,
            data_len,
            meta_len,
            use_sgl,
            single_segment,
            sqe,
            descriptors,
        )
    )

    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")

    for node in common_callchain:
        if "sym" in node:
            print(
                "	[%x] %s%s%s%s"
                % (
                    node["ip"],
                    node["sym"]["name"],
                    "+0x{:x}".format(node["sym_off"]) if "sym_off" in node else "",
                    " ({})".format(node["dso"]) if "dso" in node else "",
                    " " + node["sym_srcline"] if "sym_srcline" in node else "",
                )
            )
        else:
            print("	[%x]" % (node["ip"]))

    print()


def trace_unhandled(event_name, context, event_fields_dict, perf_sample_dict):
    print(get_dict_as_string(event_fields_dict))
    print("Sample: {" + get_dict_as_string(perf_sample_dict["sample"], ", ") + "}")


def print_header(event_name, cpu, secs, nsecs, pid, comm):
    print(
        "%-20s %5u %05u.%09u %8u %-20s " % (event_name, cpu, secs, nsecs, pid, comm),
        end="",
    )


def get_dict_as_string(a_dict, delimiter=" "):
    return delimiter.join(["%s=%s" % (k, str(v)) for k, v in sorted(a_dict.items())])
