# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

from __future__ import print_function

import os
import sys

sys.path.append(
    os.environ["PERF_EXEC_PATH"] + "/scripts/python/Perf-Trace-Util/lib/Perf/Trace"
)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from perf_trace_context import *  # noqa: F403
from Core import *  # noqa: F403
from nvme_trace_events import (
    NvmePciComplete,
    NvmePciSubmit,
    parse_complete,
    parse_submit,
)

# current queue depth per (ctrl_id, qid)
_depth: dict = {}

# histogram: (ctrl_id, qid) -> {depth: count}
_buckets: dict = {}

# in-flight commands for sanity check: (ctrl_id, qid, cid) -> True
_in_flight: dict = {}


def trace_begin():
    pass


def trace_end():
    for inf_key in sorted(_in_flight):
        ctrl_id, qid, cid = inf_key
        print(
            f"WARNING: unmatched submit ctrl_id={ctrl_id} qid={qid} cid={cid} (no completion seen)"
        )

    print("\nQueue depth histogram:")
    for queue_key in sorted(_buckets):
        ctrl_id, qid = queue_key
        print(f"  ctrl_id={ctrl_id} qid={qid}")
        for depth in sorted(_buckets[queue_key]):
            print(f"    depth {depth:4d}: {_buckets[queue_key][depth]} transactions")


def nvme__nvme_pci_submit(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    opcode,
    nsid,
    data_len,
    meta_len,
    use_sgl,
    single_segment,
    sqe,
    descriptors,
    perf_sample_dict,
):
    ev: NvmePciSubmit = parse_submit(
        ctrl_id,
        qid,
        cid,
        opcode,
        nsid,
        data_len,
        meta_len,
        use_sgl,
        single_segment,
        sqe,
        descriptors,
    )

    inf_key = (ev.ctrl_id, ev.qid, ev.cid)
    if inf_key in _in_flight:
        print(
            f"WARNING: duplicate submit ctrl_id={ev.ctrl_id} qid={ev.qid} cid={ev.cid} (no completion between submits)"
        )

    queue_key = (ev.ctrl_id, ev.qid)
    _depth[queue_key] = _depth.get(queue_key, 0) + 1
    depth = _depth[queue_key]

    buckets = _buckets.setdefault(queue_key, {})
    buckets[depth] = buckets.get(depth, 0) + 1

    _in_flight[inf_key] = True


def nvme__nvme_pci_complete(
    event_name,
    context,
    common_cpu,
    common_secs,
    common_nsecs,
    common_pid,
    common_comm,
    common_callchain,
    ctrl_id,
    qid,
    cid,
    result,
    sq_head,
    sq_id,
    status,
    retries,
    perf_sample_dict,
):
    ev: NvmePciComplete = parse_complete(
        ctrl_id, qid, cid, result, sq_head, sq_id, status, retries
    )

    inf_key = (ev.ctrl_id, ev.qid, ev.cid)
    if inf_key not in _in_flight:
        print(
            f"WARNING: completion without submit ctrl_id={ev.ctrl_id} qid={ev.qid} cid={ev.cid}"
        )
    else:
        del _in_flight[inf_key]

    queue_key = (ev.ctrl_id, ev.qid)
    current = _depth.get(queue_key, 0)
    if current <= 0:
        print(f"WARNING: queue depth underflow ctrl_id={ev.ctrl_id} qid={ev.qid}")
    else:
        _depth[queue_key] = current - 1


def trace_unhandled(event_name, context, event_fields_dict, perf_sample_dict):
    pass
